services:
  - type: web
    name: shopnow
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NEXT_PUBLIC_APP_URL
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: AUTH_SECRET
        sync: false
      - key: AUTH_GOOGLE_ID
        sync: false
      - key: AUTH_GOOGLE_SECRET
        sync: false
      - key: AUTH_FACEBOOK_ID
        sync: false
      - key: AUTH_FACEBOOK_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
